name: Bot Lavoro Roma

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ricerca Roma
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python -c "
          import requests
          import os

          msg = '✅ Dr. Confalone, assistente attivo per Roma: Implantologia guidata, Protesi e Piccola chirurgia (Giovedì).'
          url = f'https://api.telegram.org/bot{os.environ[\"TELEGRAM_TOKEN\"]}/sendMessage?chat_id={os.environ[\"CHAT_ID\"]}&text={msg}'
          requests.get(url)
          "
